/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistasParqueadero;

import funcionalidadesParqueadero.Estacionamiento;
import funcionalidadesParqueadero.EstacionamientosTotal;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class ConsultarDisponibilidad extends javax.swing.JPanel {
    private JTable table;
    private DefaultTableModel tableModel;
    private EstacionamientosTotal estacionamientosTotal;
    /**
     * Creates new form ConsultarDisponibilidad
     */
     public ConsultarDisponibilidad() {
        this.estacionamientosTotal = new EstacionamientosTotal();
        initComponents();
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(102, 102, 255));
        setPreferredSize(new java.awt.Dimension(1150, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Disponibilidad");
        jLabel1.setToolTipText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ocupado", "Fila", "Columna", "Categoría"
            }
        ));
        jTable1.setMaximumSize(new java.awt.Dimension(650, 80));
        jTable1.setName(""); // NOI18N
        jTable1.setPreferredSize(new java.awt.Dimension(650, 80));
        jTable1.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jLabel1)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
    }// </editor-fold>//GEN-END:initComponents
       
    private void initTable() {
        // Obtiene la matriz de estacionamiento desde de EstacionamientosTotal
        Estacionamiento[][] estacionamientos = estacionamientosTotal.getEstacionamientos();

        // Crear el modelo de tabla con las columnas adecuadas
        String[] columnNames = {"Estacionamientos 1", "Estacionamientos 2", "Estacionamientos 3", "Estacionamientos 4", "Estacionamientos 5", "Estacionamientos 6", "Estacionamientos 7"};
        tableModel = new DefaultTableModel(columnNames, 0);

        // Cargar los datos de los estacionamientos en el modelo de tabla
        for (int fila = 0; fila < estacionamientos.length; fila++) {
            for (int columna = 0; columna < estacionamientos.length; columna++) {
                Estacionamiento estacionamiento = estacionamientos[fila][columna];
             
                /*boolean ocupado = estacionamiento.obtenerOcupado();
                char letraFila = estacionamiento.obtenerFila();
                byte numColumna = estacionamiento.obtenerColumna();
                String categoria = estacionamiento.obtenerCategoria();*/
                
                String espacioUno = estacionamiento.obtenerFila() + String.valueOf(estacionamiento.obtenerColumna()) + estacionamiento.obtenerCategoria();
                String espacioDos = estacionamiento.obtenerFila() + String.valueOf(estacionamiento.obtenerColumna()) + estacionamiento.obtenerCategoria();
                String espacioTres = estacionamiento.obtenerFila() + String.valueOf(estacionamiento.obtenerColumna()) + estacionamiento.obtenerCategoria();
                String espacioCuatro = estacionamiento.obtenerFila() + String.valueOf(estacionamiento.obtenerColumna()) + estacionamiento.obtenerCategoria();
                String espacioCinco = estacionamiento.obtenerFila() + String.valueOf(estacionamiento.obtenerColumna()) + estacionamiento.obtenerCategoria();
                String espacioSeis = estacionamiento.obtenerFila() + String.valueOf(estacionamiento.obtenerColumna()) + estacionamiento.obtenerCategoria();
                String espacioSiete = estacionamiento.obtenerFila() + String.valueOf(estacionamiento.obtenerColumna()) + estacionamiento.obtenerCategoria();
               
                Object[] rowData = {espacioUno, espacioDos, espacioTres,espacioCuatro,espacioCinco,espacioSeis,espacioSiete};
                //tableModel.addRow(rowData);
                tableModel.addRow(rowData);
               
            }
        }

        // Asignar el modelo de tabla al JTable
        jTable1.setModel(tableModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
